#! /bin/bash

IP_ADDRESSES=(
    "192.168.1.100"
    #"10.42.0.93"
    # "192.168.1.109"
    )
USER=robot
REMOTE_DIR=sync
PASSWORD=maker

echo Copying files to 'sync' directory.
cp ../dist/D_ARM/GNU-Linux-x86/ev3dev ev3dev_d
cp ../dist/R_ARM/GNU-Linux-x86/ev3dev ev3dev

echo Devices ip addresses:

for i in ${IP_ADDRESSES[@]}; do
    echo - ${i}
done

if [ "$PASSWORD" == "" ]; then
    read -s -p "Enter password: " PASSWORD
fi

for i in ${IP_ADDRESSES[@]}; do
    sshpass -p $PASSWORD rsync -avh --delete --update ./ $USER@${i}:/home/$USER/$REMOTE_DIR ;
done
